#!/usr/bin/env bash
# Exit immediately if a command exits with a non-zero status or undefined variables are used
set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <input.lrc> <output.mp4>"
    exit 1
fi

LRC_FILE="$1"
OUT_MP4="$2"
ASS_FILE="${LRC_FILE%.*}.ass"
DURATION_FILE=$(mktemp)

echo "Processing: $LRC_FILE..."

# 1. Parse LRC and generate ASS file using awk
awk '
BEGIN {
    # Print ASS Header for FFmpeg text styling
    print "[Script Info]"
    print "Title: Silent Karaoke"
    print "ScriptType: v4.00+"
    print "PlayDepth: 0"
    print ""
    print "[V4+ Styles]"
    print "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
    # Alignment 5 = perfectly centered text. White text with black outline.
    print "Style: Default,Arial,28,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,5,10,10,10,1"
    print ""
    print "[Events]"
    print "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
    count = 0
}
{
    # Skip empty lines or non-timestamped metadata tags like [ti:Title]
    if ($0 !~ /^\[[0-9]+:[0-9]+\.[0-9]+\]/) next;

    # Extract time string and text content safely
    split($0, parts, "]");
    time_str = substr(parts[1], 2);
    text_str = substr($0, length(parts[1]) + 2);

    # Parse minutes and seconds
    split(time_str, t, ":");
    min = t[1] + 0;
    sec = t[2] + 0;

    # Convert to required ASS time format (H:MM:SS.cs)
    h = int(min / 60);
    m = min % 60;
    start_time = sprintf("%d:%02d:%05.2f", h, m, sec);

    # Print the previous line dialogue now that we know when it ends
    if (count > 0 && prev_text != "") {
        print "Dialogue: 0," prev_start "," start_time ",Default,,0,0,0,," prev_text
    }

    prev_start = start_time;
    prev_text = text_str;
    last_sec = sec;
    last_min = min;
    count++;
}
END {
    if (count == 0) exit;

    # Add a 5-second hold for the final lyric line
    end_sec = last_sec + 5;
    end_min = last_min;
    if (end_sec >= 60) {
        end_min += int(end_sec / 60);
        end_sec = end_sec % 60;
    }
    
    h = int(end_min / 60);
    m = end_min % 60;
    end_time = sprintf("%d:%02d:%05.2f", h, m, end_sec);

    if (prev_text != "") {
        print "Dialogue: 0," prev_start "," end_time ",Default,,0,0,0,," prev_text
    }

    # Calculate total video duration in seconds (plus 3 seconds padding)
    total_duration = end_min * 60 + end_sec + 3;
    print total_duration > "'"$DURATION_FILE"'";
}
' "$LRC_FILE" > "$ASS_FILE"

# Extract the total duration generated by awk
DURATION=$(cat "$DURATION_FILE")
rm -f "$DURATION_FILE"

if [ -z "$DURATION" ]; then
    echo "Error: Could not calculate duration. Is the LRC file formatted correctly?"
    exit 1
fi

echo "Subtitle converted: $ASS_FILE"
echo "Video duration set to: $DURATION seconds"
echo "Executing FFmpeg..."

# 2. Render Video
ffmpeg -y \
    -f lavfi \
    -i "color=c=black:s=1920x1080:d=${DURATION}" \
    -vf "ass='${ASS_FILE}'" \
    -c:v libx264 \
    -pix_fmt yuv420p \
    -an \
    "$OUT_MP4" > /dev/null 2>&1

echo "Success! Video saved to $OUT_MP4"
